import type { Metadata } from 'next'
import { Lato } from 'next/font/google'
import './globals.css'
import Header from './header'
import { AuthProvider } from '@/contexts/authContext'

export const metadata: Metadata = {
  title: 'Gamified voting system',
  description: 'Generated by create next app',
}

const font = Lato({ weight: '700', subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <link rel="icon" type="image/png" href="/favicon.png" />
      <body className={font.className}>
        <AuthProvider>
          <div className="min-h-screen flex flex-col">
            <Header />
            <main className="flex-1 flex flex-col items-center justify-center">
              {children}
            </main>
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
