import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Gamified voting system',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <link rel="icon" type="image/png" href="/favicon.png" />
      <body>{children}</body>
    </html>
  )
}
